include: package:lints/recommended.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    - await_only_futures
    - avoid_void_async
    - discarded_futures
    - unawaited_futures

dart_code_metrics:
  rules:
    - avoid-redundant-async