name: async_bench
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  benchmark_harness: ^2.2.2

dev_dependencies:
  dart_code_metrics: ^5.7.6
  lints: ^2.1.1
